/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.happywedding.view.manage;

/**
 *
 * @author ADMIN
 */
public class ChiPhiPhatSinh extends javax.swing.JFrame {

    /**
     * Creates new form ChiPhiPhatSinh
     */
    public ChiPhiPhatSinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMaNH25 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCPPSThamTraiBan = new javax.swing.JTextField();
        txtCPPSThamTraiBan1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblMaNH26 = new javax.swing.JLabel();
        txtCPPSThamTraiBan2 = new javax.swing.JTextField();
        txtCPPSThamTraiBan3 = new javax.swing.JTextField();
        lblMaNH27 = new javax.swing.JLabel();
        txtCPPSThamTraiBan4 = new javax.swing.JTextField();
        txtCPPSThamTraiBan5 = new javax.swing.JTextField();
        lblMaNH28 = new javax.swing.JLabel();
        txtCPPSThamTraiBan6 = new javax.swing.JTextField();
        txtCPPSThamTraiBan7 = new javax.swing.JTextField();
        lblMaNH29 = new javax.swing.JLabel();
        txtCPPSThamTraiBan8 = new javax.swing.JTextField();
        txtCPPSThamTraiBan9 = new javax.swing.JTextField();
        lblMaNH30 = new javax.swing.JLabel();
        txtCPPSThamTraiBan10 = new javax.swing.JTextField();
        txtCPPSThamTraiBan11 = new javax.swing.JTextField();
        lblMaNH31 = new javax.swing.JLabel();
        txtCPPSThamTraiBan12 = new javax.swing.JTextField();
        txtCPPSThamTraiBan13 = new javax.swing.JTextField();
        btnXacNhan = new com.ui.swing.HoverButton();
        btnBoQua = new com.ui.swing.HoverButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMaNH25.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH25.setText("Trang trí cổng");
        jPanel1.add(lblMaNH25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Chi phí phát sinh");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        txtCPPSThamTraiBan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSThamTraiBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSThamTraiBanActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPPSThamTraiBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 270, 35));

        txtCPPSThamTraiBan1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSThamTraiBan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSThamTraiBan1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPPSThamTraiBan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 360, 35));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Lý do");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        lblMaNH26.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH26.setText("Trang trí bàn tiệc");
        jPanel1.add(lblMaNH26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 120, 30));

        txtCPPSThamTraiBan2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSThamTraiBan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSThamTraiBan2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPPSThamTraiBan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 270, 35));

        txtCPPSThamTraiBan3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSThamTraiBan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSThamTraiBan3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPPSThamTraiBan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 360, 35));

        lblMaNH27.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH27.setText("Trang trí sân khấu");
        jPanel1.add(lblMaNH27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, 30));

        txtCPPSThamTraiBan4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSThamTraiBan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSThamTraiBan4ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPPSThamTraiBan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 270, 35));

        txtCPPSThamTraiBan5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSThamTraiBan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSThamTraiBan5ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPPSThamTraiBan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 360, 35));

        lblMaNH28.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH28.setText("Trang trí cổng");
        jPanel1.add(lblMaNH28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 100, 30));

        txtCPPSThamTraiBan6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSThamTraiBan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSThamTraiBan6ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPPSThamTraiBan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 270, 35));

        txtCPPSThamTraiBan7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSThamTraiBan7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSThamTraiBan7ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPPSThamTraiBan7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 360, 35));

        lblMaNH29.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH29.setText("Đặt món");
        jPanel1.add(lblMaNH29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 100, 30));

        txtCPPSThamTraiBan8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSThamTraiBan8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSThamTraiBan8ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPPSThamTraiBan8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 270, 35));

        txtCPPSThamTraiBan9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSThamTraiBan9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSThamTraiBan9ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPPSThamTraiBan9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 360, 35));

        lblMaNH30.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH30.setText("Nghệ thuật");
        jPanel1.add(lblMaNH30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 100, 30));

        txtCPPSThamTraiBan10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSThamTraiBan10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSThamTraiBan10ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPPSThamTraiBan10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 270, 35));

        txtCPPSThamTraiBan11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSThamTraiBan11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSThamTraiBan11ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPPSThamTraiBan11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 360, 35));

        lblMaNH31.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH31.setText("Đi kèm");
        jPanel1.add(lblMaNH31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 100, 30));

        txtCPPSThamTraiBan12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSThamTraiBan12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSThamTraiBan12ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPPSThamTraiBan12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 270, 35));

        txtCPPSThamTraiBan13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSThamTraiBan13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSThamTraiBan13ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPPSThamTraiBan13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 360, 35));

        btnXacNhan.setBackground(new java.awt.Color(24, 153, 29));
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.setBorderColor(new java.awt.Color(24, 153, 29));
        btnXacNhan.setColor(new java.awt.Color(24, 153, 29));
        btnXacNhan.setColorClick(new java.awt.Color(0, 204, 0));
        btnXacNhan.setColorOver(new java.awt.Color(0, 204, 0));
        btnXacNhan.setFocusPainted(false);
        btnXacNhan.setLabelColor(java.awt.Color.white);
        btnXacNhan.setLableColorClick(java.awt.Color.white);
        btnXacNhan.setRadius(15);
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        jPanel1.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, -1, 30));

        btnBoQua.setBackground(new java.awt.Color(24, 37, 153));
        btnBoQua.setForeground(new java.awt.Color(255, 255, 255));
        btnBoQua.setText("Bỏ qua");
        btnBoQua.setBorderColor(new java.awt.Color(24, 37, 153));
        btnBoQua.setColor(new java.awt.Color(24, 37, 153));
        btnBoQua.setColorClick(new java.awt.Color(51, 51, 255));
        btnBoQua.setColorOver(new java.awt.Color(51, 51, 255));
        btnBoQua.setFocusPainted(false);
        btnBoQua.setLabelColor(java.awt.Color.white);
        btnBoQua.setLableColorClick(java.awt.Color.white);
        btnBoQua.setRadius(15);
        btnBoQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoQuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBoQua, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCPPSThamTraiBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSThamTraiBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSThamTraiBanActionPerformed

    private void txtCPPSThamTraiBan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSThamTraiBan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSThamTraiBan1ActionPerformed

    private void txtCPPSThamTraiBan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSThamTraiBan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSThamTraiBan2ActionPerformed

    private void txtCPPSThamTraiBan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSThamTraiBan3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSThamTraiBan3ActionPerformed

    private void txtCPPSThamTraiBan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSThamTraiBan4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSThamTraiBan4ActionPerformed

    private void txtCPPSThamTraiBan5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSThamTraiBan5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSThamTraiBan5ActionPerformed

    private void txtCPPSThamTraiBan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSThamTraiBan6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSThamTraiBan6ActionPerformed

    private void txtCPPSThamTraiBan7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSThamTraiBan7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSThamTraiBan7ActionPerformed

    private void txtCPPSThamTraiBan8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSThamTraiBan8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSThamTraiBan8ActionPerformed

    private void txtCPPSThamTraiBan9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSThamTraiBan9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSThamTraiBan9ActionPerformed

    private void txtCPPSThamTraiBan10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSThamTraiBan10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSThamTraiBan10ActionPerformed

    private void txtCPPSThamTraiBan11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSThamTraiBan11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSThamTraiBan11ActionPerformed

    private void txtCPPSThamTraiBan12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSThamTraiBan12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSThamTraiBan12ActionPerformed

    private void txtCPPSThamTraiBan13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSThamTraiBan13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSThamTraiBan13ActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnBoQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoQuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBoQuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiPhiPhatSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiPhiPhatSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiPhiPhatSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiPhiPhatSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiPhiPhatSinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ui.swing.HoverButton btnBoQua;
    private com.ui.swing.HoverButton btnXacNhan;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMaNH25;
    private javax.swing.JLabel lblMaNH26;
    private javax.swing.JLabel lblMaNH27;
    private javax.swing.JLabel lblMaNH28;
    private javax.swing.JLabel lblMaNH29;
    private javax.swing.JLabel lblMaNH30;
    private javax.swing.JLabel lblMaNH31;
    private javax.swing.JTextField txtCPPSThamTraiBan;
    private javax.swing.JTextField txtCPPSThamTraiBan1;
    private javax.swing.JTextField txtCPPSThamTraiBan10;
    private javax.swing.JTextField txtCPPSThamTraiBan11;
    private javax.swing.JTextField txtCPPSThamTraiBan12;
    private javax.swing.JTextField txtCPPSThamTraiBan13;
    private javax.swing.JTextField txtCPPSThamTraiBan2;
    private javax.swing.JTextField txtCPPSThamTraiBan3;
    private javax.swing.JTextField txtCPPSThamTraiBan4;
    private javax.swing.JTextField txtCPPSThamTraiBan5;
    private javax.swing.JTextField txtCPPSThamTraiBan6;
    private javax.swing.JTextField txtCPPSThamTraiBan7;
    private javax.swing.JTextField txtCPPSThamTraiBan8;
    private javax.swing.JTextField txtCPPSThamTraiBan9;
    // End of variables declaration//GEN-END:variables
}
