/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.happywedding.view.manage;

import com.happywedding.dao.NhanVienDAO;
import com.happywedding.dao.PhanCongDAO;
import com.happywedding.dao.PhongBanDAO;
import com.happywedding.dao.VaiTroDAO;
import com.happywedding.helper.AppStatus;
import com.happywedding.helper.ShareHelper;
import com.happywedding.model.ChiTietDatMon;
import com.happywedding.model.MonAn;
import com.happywedding.model.NhanVien;
import com.happywedding.model.PhanCongModel;
import com.happywedding.model.PhongBan;
import com.happywedding.model.VaiTro;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class ChonNhanVien extends javax.swing.JDialog {

    /**
     * Creates new form ChonNhanVien
     */
    private DefaultTableModel tblNhanVienModel;
    private List<NhanVien> listNhanVien = new ArrayList<>();

    private List<PhongBan> listAllPhongBan;
    private List<VaiTro> listAllVaiTro;

    private VaiTroDAO vaitroDAO = new VaiTroDAO();
    private PhongBanDAO phongBanDAO = new PhongBanDAO();
    private NhanVienDAO nhanVienDAO = new NhanVienDAO();
    private PhanCongDAO phanCongDAO = new PhanCongDAO();
    private String maHD ;

    public ChonNhanVien(java.awt.Frame parent, boolean modal, String maHD) {
        super(parent, modal);
        initComponents();
        this.maHD = maHD;
        tblNhanVien.fixTable(jScrollPane1);
        tblNhanVienModel = (DefaultTableModel) tblNhanVien.getModel();

        loadNhanVien();
        loadPhongBan();
        fillTableNhanVien(listNhanVien);
    }

    public void loadNhanVien() {
        listNhanVien = phanCongDAO.selectNhanVienPossible(maHD);
    }

    public void loadPhongBan() {
        listAllPhongBan = phongBanDAO.select();

        DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cbbPhongBan.getModel();
        cbbModel.removeAllElements();
        for (PhongBan s : listAllPhongBan) {
            cbbModel.addElement(s);
        }
        cbbPhongBan.setSelectedIndex(-1);
    }

    public void fillTableNhanVien(List<NhanVien> list) {
        tblNhanVienModel.setRowCount(0);

        for (NhanVien nv : list) {
            Object[] row = {nv.getMaNV(), nv.getHoTen(), nv.getTenVT()};
            tblNhanVienModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new com.ui.swing.Table();
        jLabel11 = new javax.swing.JLabel();
        cbbPhongBan = new com.ui.swing.Combobox();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbbVaiTro = new com.ui.swing.Combobox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ Tên", "Vai trò"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 490, 560));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Phòng ban");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        cbbPhongBan.setLabeText("");
        cbbPhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPhongBanActionPerformed(evt);
            }
        });
        jPanel1.add(cbbPhongBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/happywedding/assets/Search.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 40));

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtTimKiem.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });
        jPanel1.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 410, 35));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Vai trò");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        cbbVaiTro.setLabeText("");
        cbbVaiTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbVaiTroActionPerformed(evt);
            }
        });
        jPanel1.add(cbbVaiTro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbbPhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPhongBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbPhongBanActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased

    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        int currentIndex = tblNhanVien.getSelectedRow();
        if (currentIndex > -1) {
            if (evt.getClickCount() >= 2) {
                AppStatus.PHANCONG.phanCongMoi(listNhanVien.get(currentIndex));
                this.dispose();
            }
        }

    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void cbbVaiTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbVaiTroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbVaiTroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ui.swing.Combobox cbbPhongBan;
    private com.ui.swing.Combobox cbbVaiTro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.ui.swing.Table tblNhanVien;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
