/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.happywedding.view.manage;

import com.happywedding.helper.AppStatus;
import com.ui.swing.Combobox;
import java.awt.Component;
import javax.swing.JTextField;




/**
 *
 * @author ADMIN
 */
public class NgheThuat extends javax.swing.JDialog {
     private String maHD;
     private boolean isCreate;
     private final String maDV = "NGHETHUAT";
     
      static class VatTrangTri {

        static final String VUDAO = "VUDAO";
        static final String LIENKHUC = "LIENKHUC";
        

    }
     
    /**
     * Creates new form NgheThuat
     */
    public NgheThuat(java.awt.Frame parent, boolean modal, String maHD) {
       super(parent, modal);
        this.maHD = maHD;
        this.isCreate = modal;
        initComponents();
        init();
    }

    public void init() {
        isView(isCreate);
    }

    public void isView(boolean isCreate) {
        for (Component cp : pnlNgheThuat.getComponents()) {
            if (cp instanceof JTextField) {
                cp.setEnabled(isCreate);
            } else if (cp instanceof Combobox) {
                cp.setEnabled(isCreate);
            }

        }
        btnSave.setVisible(isCreate);
        btnReset.setVisible(isCreate);
        btnEdit.setVisible(isCreate);
        taGhiChu.setEnabled(isCreate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNgheThuat = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblMaNH18 = new javax.swing.JLabel();
        cbbGoiDV = new com.ui.swing.Combobox();
        btnEdit = new com.ui.swing.HoverButton();
        jLabel5 = new javax.swing.JLabel();
        lblMaNH19 = new javax.swing.JLabel();
        cbbVuDao = new com.ui.swing.Combobox();
        lblMaNH24 = new javax.swing.JLabel();
        lblMaNH25 = new javax.swing.JLabel();
        cbbAmNhac = new com.ui.swing.Combobox();
        txtGCAmNhac = new javax.swing.JTextField();
        txtGCVuDao = new javax.swing.JTextField();
        txtChiPhi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCPPSAmNhac = new javax.swing.JTextField();
        txtCPPSVuDao = new javax.swing.JTextField();
        lblMaNH8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taGhiChu = new javax.swing.JTextArea();
        txtTongCPPS = new javax.swing.JTextField();
        txtTongChiPhi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSave = new com.ui.swing.HoverButton();
        btnReset = new com.ui.swing.HoverButton();
        jLabel10 = new javax.swing.JLabel();
        txtCPAmNhac = new javax.swing.JTextField();
        txtCPVuDao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlNgheThuat.setBackground(new java.awt.Color(255, 255, 255));
        pnlNgheThuat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Tổng chi phí phải trả");
        pnlNgheThuat.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 420, -1, -1));

        lblMaNH18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH18.setText("Gói");
        pnlNgheThuat.add(lblMaNH18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 50, 30));

        cbbGoiDV.setToolTipText("");
        cbbGoiDV.setLabeText("");
        cbbGoiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbGoiDVActionPerformed(evt);
            }
        });
        pnlNgheThuat.add(cbbGoiDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 320, 35));

        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Tùy chỉnh");
        btnEdit.setBorderColor(new java.awt.Color(153, 24, 24));
        btnEdit.setColor(new java.awt.Color(153, 24, 24));
        btnEdit.setColorClick(new java.awt.Color(255, 51, 51));
        btnEdit.setColorOver(new java.awt.Color(255, 51, 51));
        btnEdit.setFocusPainted(false);
        btnEdit.setLabelColor(java.awt.Color.white);
        btnEdit.setLableColorClick(java.awt.Color.white);
        btnEdit.setRadius(15);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        pnlNgheThuat.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Nghệ thuật");
        pnlNgheThuat.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblMaNH19.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH19.setText("Vũ đạo");
        pnlNgheThuat.add(lblMaNH19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 90, 30));

        cbbVuDao.setToolTipText("");
        cbbVuDao.setLabeText("");
        cbbVuDao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbVuDaoActionPerformed(evt);
            }
        });
        pnlNgheThuat.add(cbbVuDao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 330, 35));

        lblMaNH24.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH24.setText("Chi phí");
        pnlNgheThuat.add(lblMaNH24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 90, 30));

        lblMaNH25.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH25.setText("Âm nhạc");
        pnlNgheThuat.add(lblMaNH25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 100, 30));

        cbbAmNhac.setToolTipText("");
        cbbAmNhac.setLabeText("");
        cbbAmNhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbAmNhacActionPerformed(evt);
            }
        });
        pnlNgheThuat.add(cbbAmNhac, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 330, 35));

        txtGCAmNhac.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtGCAmNhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGCAmNhacActionPerformed(evt);
            }
        });
        pnlNgheThuat.add(txtGCAmNhac, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 360, 35));

        txtGCVuDao.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        pnlNgheThuat.add(txtGCVuDao, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 360, 35));

        txtChiPhi.setEditable(false);
        txtChiPhi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtChiPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChiPhiActionPerformed(evt);
            }
        });
        pnlNgheThuat.add(txtChiPhi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 330, 35));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Tiết mục");
        pnlNgheThuat.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Chi phí phát sinh");
        pnlNgheThuat.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 170, -1, -1));

        txtCPPSAmNhac.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSAmNhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSAmNhacActionPerformed(evt);
            }
        });
        pnlNgheThuat.add(txtCPPSAmNhac, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 230, 170, 35));

        txtCPPSVuDao.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        pnlNgheThuat.add(txtCPPSVuDao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 290, 170, 35));

        lblMaNH8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH8.setText("Ghi chú");
        pnlNgheThuat.add(lblMaNH8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 60, -1));

        taGhiChu.setColumns(20);
        taGhiChu.setRows(5);
        jScrollPane1.setViewportView(taGhiChu);

        pnlNgheThuat.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 330, 80));

        txtTongCPPS.setEditable(false);
        txtTongCPPS.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTongCPPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongCPPSActionPerformed(evt);
            }
        });
        pnlNgheThuat.add(txtTongCPPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 360, 35));

        txtTongChiPhi.setEditable(false);
        txtTongChiPhi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTongChiPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongChiPhiActionPerformed(evt);
            }
        });
        pnlNgheThuat.add(txtTongChiPhi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 470, 360, 35));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Ghi chú");
        pnlNgheThuat.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Tổng chi phát phát sinh");
        pnlNgheThuat.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        btnSave.setBackground(new java.awt.Color(24, 153, 29));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Lưu");
        btnSave.setBorderColor(new java.awt.Color(24, 153, 29));
        btnSave.setColor(new java.awt.Color(24, 153, 29));
        btnSave.setColorClick(new java.awt.Color(0, 204, 0));
        btnSave.setColorOver(new java.awt.Color(0, 204, 0));
        btnSave.setFocusPainted(false);
        btnSave.setLabelColor(java.awt.Color.white);
        btnSave.setLableColorClick(java.awt.Color.white);
        btnSave.setRadius(15);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlNgheThuat.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 550, -1, 30));

        btnReset.setBackground(new java.awt.Color(24, 37, 153));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Làm mới");
        btnReset.setBorderColor(new java.awt.Color(24, 37, 153));
        btnReset.setColor(new java.awt.Color(24, 37, 153));
        btnReset.setColorClick(new java.awt.Color(51, 51, 255));
        btnReset.setColorOver(new java.awt.Color(51, 51, 255));
        btnReset.setFocusPainted(false);
        btnReset.setLabelColor(java.awt.Color.white);
        btnReset.setLableColorClick(java.awt.Color.white);
        btnReset.setRadius(15);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        pnlNgheThuat.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 550, -1, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Chi phí");
        pnlNgheThuat.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        txtCPAmNhac.setEditable(false);
        txtCPAmNhac.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPAmNhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPAmNhacActionPerformed(evt);
            }
        });
        pnlNgheThuat.add(txtCPAmNhac, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 170, 35));

        txtCPVuDao.setEditable(false);
        txtCPVuDao.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        pnlNgheThuat.add(txtCPVuDao, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 170, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNgheThuat, javax.swing.GroupLayout.PREFERRED_SIZE, 1446, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNgheThuat, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbbGoiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbGoiDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbGoiDVActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void cbbVuDaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbVuDaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbVuDaoActionPerformed

    private void cbbAmNhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbAmNhacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbAmNhacActionPerformed

    private void txtGCAmNhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGCAmNhacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGCAmNhacActionPerformed

    private void txtChiPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChiPhiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChiPhiActionPerformed

    private void txtCPPSAmNhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSAmNhacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSAmNhacActionPerformed

    private void txtTongCPPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongCPPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongCPPSActionPerformed

    private void txtTongChiPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongChiPhiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongChiPhiActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         AppStatus.lapHopDong.reloadHopDong();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtCPAmNhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPAmNhacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPAmNhacActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ui.swing.HoverButton btnEdit;
    private com.ui.swing.HoverButton btnReset;
    private com.ui.swing.HoverButton btnSave;
    private com.ui.swing.Combobox cbbAmNhac;
    private com.ui.swing.Combobox cbbGoiDV;
    private com.ui.swing.Combobox cbbVuDao;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMaNH18;
    private javax.swing.JLabel lblMaNH19;
    private javax.swing.JLabel lblMaNH24;
    private javax.swing.JLabel lblMaNH25;
    private javax.swing.JLabel lblMaNH8;
    private javax.swing.JPanel pnlNgheThuat;
    private javax.swing.JTextArea taGhiChu;
    private javax.swing.JTextField txtCPAmNhac;
    private javax.swing.JTextField txtCPPSAmNhac;
    private javax.swing.JTextField txtCPPSVuDao;
    private javax.swing.JTextField txtCPVuDao;
    private javax.swing.JTextField txtChiPhi;
    private javax.swing.JTextField txtGCAmNhac;
    private javax.swing.JTextField txtGCVuDao;
    private javax.swing.JTextField txtTongCPPS;
    private javax.swing.JTextField txtTongChiPhi;
    // End of variables declaration//GEN-END:variables
}
