/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.happywedding.view.manage;

import javax.swing.JFrame;

/**
 *
 * @author ADMIN
 */
public class PhanCong extends javax.swing.JDialog {

    /**
     * Creates new form PhanCong
     */
    public PhanCong(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUpdate3 = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        lblSort = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtVaiTro = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtNgayPhanCong = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtBatDau = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtKetThuc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbbXe = new com.ui.swing.Combobox();
        btnSua = new com.ui.swing.InkwellButton();
        btnXoa = new com.ui.swing.InkwellButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVien = new com.ui.swing.Table();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlUpdate3.setBackground(new java.awt.Color(255, 255, 255));
        pnlUpdate3.setMinimumSize(new java.awt.Dimension(1600, 838));
        pnlUpdate3.setPreferredSize(new java.awt.Dimension(1680, 1000));
        pnlUpdate3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSearch.setBackground(new java.awt.Color(204, 204, 255));
        lblSearch.setForeground(new java.awt.Color(102, 0, 255));
        lblSearch.setAutoscrolls(true);
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
        });
        pnlUpdate3.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 20, -1, 33));

        lblSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSortMouseClicked(evt);
            }
        });
        pnlUpdate3.add(lblSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 32, 35));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setText("Mã nhân viên");
        pnlUpdate3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        txtMaNV.setEditable(false);
        txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtMaNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaNVMouseClicked(evt);
            }
        });
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });
        pnlUpdate3.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 340, 35));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel18.setText("Họ và tên");
        pnlUpdate3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txtHoTen.setEditable(false);
        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        pnlUpdate3.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 340, 35));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel19.setText("Vai trò");
        pnlUpdate3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        txtVaiTro.setEditable(false);
        txtVaiTro.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        pnlUpdate3.add(txtVaiTro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 35));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel20.setText("Ngày phân công");
        pnlUpdate3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        txtNgayPhanCong.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        pnlUpdate3.add(txtNgayPhanCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 340, 35));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setText("Bắt đầu");
        pnlUpdate3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        txtBatDau.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        pnlUpdate3.add(txtBatDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 140, 35));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel23.setText("Kết thúc");
        pnlUpdate3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        txtKetThuc.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        pnlUpdate3.add(txtKetThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 160, 35));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel14.setText("Xe");
        pnlUpdate3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        cbbXe.setLabeText("");
        pnlUpdate3.add(cbbXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 340, -1));

        btnSua.setBackground(new java.awt.Color(0, 153, 0));
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlUpdate3.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, 80, -1));

        btnXoa.setBackground(new java.awt.Color(153, 24, 24));
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlUpdate3.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 80, -1));

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ tên nhân viên", "Vai trò", "Ngày phân công", "Bắt đầu", "Kết thúc", "Xe"
            }
        ));
        jScrollPane2.setViewportView(tblNhanVien);

        pnlUpdate3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 1200, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUpdate3, javax.swing.GroupLayout.DEFAULT_SIZE, 1600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUpdate3, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSortMouseClicked

    }//GEN-LAST:event_lblSortMouseClicked

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked

    }//GEN-LAST:event_lblSearchMouseClicked

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        new ChonNhanVien(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void txtMaNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaNVMouseClicked
      new ChonNhanVien(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_txtMaNVMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhanCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhanCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhanCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhanCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PhanCong dialog = new PhanCong(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ui.swing.InkwellButton btnSua;
    private com.ui.swing.InkwellButton btnXoa;
    private com.ui.swing.Combobox cbbXe;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSort;
    private javax.swing.JPanel pnlUpdate3;
    private com.ui.swing.Table tblNhanVien;
    private javax.swing.JTextField txtBatDau;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtKetThuc;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgayPhanCong;
    private javax.swing.JTextField txtVaiTro;
    // End of variables declaration//GEN-END:variables
}
