/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.happywedding.view.manage;

import com.happywedding.helper.AppStatus;
import com.ui.swing.Combobox;
import java.awt.Component;
import javax.swing.JTextField;

/**
 *
 * @author ADMIN
 */
public class TrangTriCong extends javax.swing.JDialog {
    
   private String maHD;
   private boolean isCreate;
     private final String maDV = "TTCONG";
     
    static class VatTrangTri {

        static final String CONG = "CONG";
        static final String HOACHUDAO = "HOACHUDAO";
        static final String HOAPHUDAO = "HOAPHUDAO";
        static final String THAM = "THAM";
        static final String BANGTEN = "BANGTEN";
        
    }
    
    
    /**
     * Creates new form TrangTriCong
     */
    public TrangTriCong(java.awt.Frame parent, boolean modal, String maHD) {
        super(parent, modal);
        this.maHD = maHD;
        this.isCreate = modal;
        initComponents();
        init();
    }
    
     public void init() {
        isView(isCreate);
    }
    
      public void isView(boolean isCreate) {
        for (Component cp : pnlTTCong.getComponents()) {
            if (cp instanceof JTextField) {
                cp.setEnabled(isCreate);
            }else if(cp instanceof Combobox)
            {
                cp.setEnabled(isCreate);
            }

        }
        btnSave.setVisible(isCreate);
        btnReset.setVisible(isCreate);
        btnEdit.setVisible(isCreate);
        taGhiChu.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTTCong = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblMaNH18 = new javax.swing.JLabel();
        cbbGoiDV = new com.ui.swing.Combobox();
        btnEdit = new com.ui.swing.HoverButton();
        jLabel5 = new javax.swing.JLabel();
        lblMaNH19 = new javax.swing.JLabel();
        cbbHoaChuDao = new com.ui.swing.Combobox();
        lblMaNH22 = new javax.swing.JLabel();
        cbbHoaPhuDao = new com.ui.swing.Combobox();
        lblMaNH23 = new javax.swing.JLabel();
        cbbTham = new com.ui.swing.Combobox();
        lblMaNH24 = new javax.swing.JLabel();
        cbbBangTen = new com.ui.swing.Combobox();
        lblMaNH25 = new javax.swing.JLabel();
        cbbCong = new com.ui.swing.Combobox();
        txtGCCong = new javax.swing.JTextField();
        txtGCHoaChuDao = new javax.swing.JTextField();
        txtGCHoaPhuDao = new javax.swing.JTextField();
        txtGCTham = new javax.swing.JTextField();
        txtChiPhi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCPPSCong = new javax.swing.JTextField();
        txtCPPSHoaChuDao = new javax.swing.JTextField();
        txtCPPSHoaPhuDao = new javax.swing.JTextField();
        txtCPPSTham = new javax.swing.JTextField();
        txtCPPSBangTen = new javax.swing.JTextField();
        lblMaNH8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taGhiChu = new javax.swing.JTextArea();
        txtGCBangTen = new javax.swing.JTextField();
        lblMaNH26 = new javax.swing.JLabel();
        txtTongCPPS = new javax.swing.JTextField();
        txtTongChiPhi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSave = new com.ui.swing.HoverButton();
        btnReset = new com.ui.swing.HoverButton();
        jLabel10 = new javax.swing.JLabel();
        txtCPCong = new javax.swing.JTextField();
        txtCPHoaChuDao = new javax.swing.JTextField();
        txtCPHoaPhuDao = new javax.swing.JTextField();
        txtCPTham = new javax.swing.JTextField();
        txtCPBangTen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlTTCong.setBackground(new java.awt.Color(255, 255, 255));
        pnlTTCong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Tổng chi phí phải trả");
        pnlTTCong.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 600, -1, -1));

        lblMaNH18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH18.setText("Gói");
        pnlTTCong.add(lblMaNH18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 50, 30));

        cbbGoiDV.setToolTipText("");
        cbbGoiDV.setLabeText("");
        cbbGoiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbGoiDVActionPerformed(evt);
            }
        });
        pnlTTCong.add(cbbGoiDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 320, 35));

        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Tùy chỉnh");
        btnEdit.setBorderColor(new java.awt.Color(153, 24, 24));
        btnEdit.setColor(new java.awt.Color(153, 24, 24));
        btnEdit.setColorClick(new java.awt.Color(255, 51, 51));
        btnEdit.setColorOver(new java.awt.Color(255, 51, 51));
        btnEdit.setFocusPainted(false);
        btnEdit.setLabelColor(java.awt.Color.white);
        btnEdit.setLableColorClick(java.awt.Color.white);
        btnEdit.setRadius(15);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        pnlTTCong.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Trang trí cổng");
        pnlTTCong.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblMaNH19.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH19.setText("Hoa chủ đạo");
        pnlTTCong.add(lblMaNH19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 90, 30));

        cbbHoaChuDao.setToolTipText("");
        cbbHoaChuDao.setLabeText("");
        cbbHoaChuDao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbHoaChuDaoActionPerformed(evt);
            }
        });
        pnlTTCong.add(cbbHoaChuDao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 330, 35));

        lblMaNH22.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH22.setText("Hoa phụ đạo");
        pnlTTCong.add(lblMaNH22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 90, 30));

        cbbHoaPhuDao.setToolTipText("");
        cbbHoaPhuDao.setLabeText("");
        cbbHoaPhuDao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbHoaPhuDaoActionPerformed(evt);
            }
        });
        pnlTTCong.add(cbbHoaPhuDao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 330, 35));

        lblMaNH23.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH23.setText("Thảm");
        pnlTTCong.add(lblMaNH23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 50, 30));

        cbbTham.setToolTipText("");
        cbbTham.setLabeText("");
        cbbTham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbThamActionPerformed(evt);
            }
        });
        pnlTTCong.add(cbbTham, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 330, 35));

        lblMaNH24.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH24.setText("Chi phí");
        pnlTTCong.add(lblMaNH24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 90, 30));

        cbbBangTen.setToolTipText("");
        cbbBangTen.setLabeText("");
        cbbBangTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbBangTenActionPerformed(evt);
            }
        });
        pnlTTCong.add(cbbBangTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 330, 35));

        lblMaNH25.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH25.setText("Cổng");
        pnlTTCong.add(lblMaNH25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 50, 30));

        cbbCong.setToolTipText("");
        cbbCong.setLabeText("");
        cbbCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbCongActionPerformed(evt);
            }
        });
        pnlTTCong.add(cbbCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 330, 35));

        txtGCCong.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtGCCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGCCongActionPerformed(evt);
            }
        });
        pnlTTCong.add(txtGCCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 360, 35));

        txtGCHoaChuDao.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        pnlTTCong.add(txtGCHoaChuDao, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, 360, 35));

        txtGCHoaPhuDao.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtGCHoaPhuDao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGCHoaPhuDaoActionPerformed(evt);
            }
        });
        pnlTTCong.add(txtGCHoaPhuDao, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 360, 35));

        txtGCTham.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtGCTham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGCThamActionPerformed(evt);
            }
        });
        pnlTTCong.add(txtGCTham, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 360, 35));

        txtChiPhi.setEditable(false);
        txtChiPhi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtChiPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChiPhiActionPerformed(evt);
            }
        });
        pnlTTCong.add(txtChiPhi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, 330, 35));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Vật trang trí");
        pnlTTCong.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Chi phí phát sinh");
        pnlTTCong.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 170, -1, -1));

        txtCPPSCong.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSCongActionPerformed(evt);
            }
        });
        pnlTTCong.add(txtCPPSCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 230, 190, 35));

        txtCPPSHoaChuDao.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        pnlTTCong.add(txtCPPSHoaChuDao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 290, 190, 35));

        txtCPPSHoaPhuDao.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSHoaPhuDao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSHoaPhuDaoActionPerformed(evt);
            }
        });
        pnlTTCong.add(txtCPPSHoaPhuDao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 350, 190, 35));

        txtCPPSTham.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSTham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSThamActionPerformed(evt);
            }
        });
        pnlTTCong.add(txtCPPSTham, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 420, 190, 35));

        txtCPPSBangTen.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPPSBangTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPSBangTenActionPerformed(evt);
            }
        });
        pnlTTCong.add(txtCPPSBangTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 490, 190, 35));

        lblMaNH8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH8.setText("Ghi chú");
        pnlTTCong.add(lblMaNH8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 60, -1));

        taGhiChu.setColumns(20);
        taGhiChu.setRows(5);
        jScrollPane1.setViewportView(taGhiChu);

        pnlTTCong.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 330, 80));

        txtGCBangTen.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtGCBangTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGCBangTenActionPerformed(evt);
            }
        });
        pnlTTCong.add(txtGCBangTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, 360, 35));

        lblMaNH26.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMaNH26.setText("Bảng tên");
        pnlTTCong.add(lblMaNH26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 90, 30));

        txtTongCPPS.setEditable(false);
        txtTongCPPS.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTongCPPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongCPPSActionPerformed(evt);
            }
        });
        pnlTTCong.add(txtTongCPPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 650, 360, 35));

        txtTongChiPhi.setEditable(false);
        txtTongChiPhi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTongChiPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongChiPhiActionPerformed(evt);
            }
        });
        pnlTTCong.add(txtTongChiPhi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 650, 360, 35));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Ghi chú");
        pnlTTCong.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, -30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Tổng chi phát phát sinh");
        pnlTTCong.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 610, -1, -1));

        btnSave.setBackground(new java.awt.Color(24, 153, 29));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Lưu");
        btnSave.setBorderColor(new java.awt.Color(24, 153, 29));
        btnSave.setColor(new java.awt.Color(24, 153, 29));
        btnSave.setColorClick(new java.awt.Color(0, 204, 0));
        btnSave.setColorOver(new java.awt.Color(0, 204, 0));
        btnSave.setFocusPainted(false);
        btnSave.setLabelColor(java.awt.Color.white);
        btnSave.setLableColorClick(java.awt.Color.white);
        btnSave.setRadius(15);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlTTCong.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 730, -1, 30));

        btnReset.setBackground(new java.awt.Color(24, 37, 153));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Làm mới");
        btnReset.setBorderColor(new java.awt.Color(24, 37, 153));
        btnReset.setColor(new java.awt.Color(24, 37, 153));
        btnReset.setColorClick(new java.awt.Color(51, 51, 255));
        btnReset.setColorOver(new java.awt.Color(51, 51, 255));
        btnReset.setFocusPainted(false);
        btnReset.setLabelColor(java.awt.Color.white);
        btnReset.setLableColorClick(java.awt.Color.white);
        btnReset.setRadius(15);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        pnlTTCong.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 730, -1, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Ghi chú");
        pnlTTCong.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, -1, -1));

        txtCPCong.setEditable(false);
        txtCPCong.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPCongActionPerformed(evt);
            }
        });
        pnlTTCong.add(txtCPCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 190, 35));

        txtCPHoaChuDao.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        pnlTTCong.add(txtCPHoaChuDao, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 190, 35));

        txtCPHoaPhuDao.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPHoaPhuDao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPHoaPhuDaoActionPerformed(evt);
            }
        });
        pnlTTCong.add(txtCPHoaPhuDao, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 190, 35));

        txtCPTham.setEditable(false);
        txtCPTham.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPTham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPThamActionPerformed(evt);
            }
        });
        pnlTTCong.add(txtCPTham, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 190, 35));

        txtCPBangTen.setEditable(false);
        txtCPBangTen.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCPBangTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPBangTenActionPerformed(evt);
            }
        });
        pnlTTCong.add(txtCPBangTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 190, 35));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Chi phí");
        pnlTTCong.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTTCong, javax.swing.GroupLayout.PREFERRED_SIZE, 1446, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTTCong, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1464, 842));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbbGoiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbGoiDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbGoiDVActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void cbbHoaChuDaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbHoaChuDaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbHoaChuDaoActionPerformed

    private void cbbHoaPhuDaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbHoaPhuDaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbHoaPhuDaoActionPerformed

    private void cbbThamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbThamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbThamActionPerformed

    private void cbbBangTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbBangTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbBangTenActionPerformed

    private void cbbCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbCongActionPerformed

    private void txtGCCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGCCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGCCongActionPerformed

    private void txtGCHoaPhuDaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGCHoaPhuDaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGCHoaPhuDaoActionPerformed

    private void txtGCThamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGCThamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGCThamActionPerformed

    private void txtChiPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChiPhiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChiPhiActionPerformed

    private void txtCPPSCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSCongActionPerformed

    private void txtCPPSHoaPhuDaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSHoaPhuDaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSHoaPhuDaoActionPerformed

    private void txtCPPSThamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSThamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSThamActionPerformed

    private void txtCPPSBangTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPSBangTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPSBangTenActionPerformed

    private void txtGCBangTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGCBangTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGCBangTenActionPerformed

    private void txtTongCPPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongCPPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongCPPSActionPerformed

    private void txtTongChiPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongChiPhiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongChiPhiActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        AppStatus.lapHopDong.reloadHopDong();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtCPCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPCongActionPerformed

    private void txtCPHoaPhuDaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPHoaPhuDaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPHoaPhuDaoActionPerformed

    private void txtCPThamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPThamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPThamActionPerformed

    private void txtCPBangTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPBangTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPBangTenActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ui.swing.HoverButton btnEdit;
    private com.ui.swing.HoverButton btnReset;
    private com.ui.swing.HoverButton btnSave;
    private com.ui.swing.Combobox cbbBangTen;
    private com.ui.swing.Combobox cbbCong;
    private com.ui.swing.Combobox cbbGoiDV;
    private com.ui.swing.Combobox cbbHoaChuDao;
    private com.ui.swing.Combobox cbbHoaPhuDao;
    private com.ui.swing.Combobox cbbTham;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMaNH18;
    private javax.swing.JLabel lblMaNH19;
    private javax.swing.JLabel lblMaNH22;
    private javax.swing.JLabel lblMaNH23;
    private javax.swing.JLabel lblMaNH24;
    private javax.swing.JLabel lblMaNH25;
    private javax.swing.JLabel lblMaNH26;
    private javax.swing.JLabel lblMaNH8;
    private javax.swing.JPanel pnlTTCong;
    private javax.swing.JTextArea taGhiChu;
    private javax.swing.JTextField txtCPBangTen;
    private javax.swing.JTextField txtCPCong;
    private javax.swing.JTextField txtCPHoaChuDao;
    private javax.swing.JTextField txtCPHoaPhuDao;
    private javax.swing.JTextField txtCPPSBangTen;
    private javax.swing.JTextField txtCPPSCong;
    private javax.swing.JTextField txtCPPSHoaChuDao;
    private javax.swing.JTextField txtCPPSHoaPhuDao;
    private javax.swing.JTextField txtCPPSTham;
    private javax.swing.JTextField txtCPTham;
    private javax.swing.JTextField txtChiPhi;
    private javax.swing.JTextField txtGCBangTen;
    private javax.swing.JTextField txtGCCong;
    private javax.swing.JTextField txtGCHoaChuDao;
    private javax.swing.JTextField txtGCHoaPhuDao;
    private javax.swing.JTextField txtGCTham;
    private javax.swing.JTextField txtTongCPPS;
    private javax.swing.JTextField txtTongChiPhi;
    // End of variables declaration//GEN-END:variables
}
