/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.happywedding.view.statical;

import com.happywedding.helper.AppStatus;

import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.border.EmptyBorder;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author ADMIN
 */
public class ThongKe extends javax.swing.JPanel {

    
    static class SUB_STATISTICAL_MANAGER {
        static int THONG_KE_NAM= 0;
        static int THONG_KE_THANG = 1;
        static int THONG_KE_DICVH = 2;
        
    }
    
    private ThongKeDichVu thongKeDichVu;
    private ThongKeDoanhThuNam thongKeNam;
    private ThongKeDoanhThuThang thongKeThang;
   
 
     private MigLayout layout;
    
    private int index = 0;
    
    
    /**
     * Creates new form StaticalForm
     */
    public ThongKe() {
        initComponents();
        
        
        setOpaque(false);
        setLayout(new BorderLayout());
        setBorder(new EmptyBorder(10, 20, 10, 20));
        tabPane.setOpaque(false);

        layout = new MigLayout("fill", "0[]0[100%, fill]0", "0[fill, top]0");
        setLayout(layout);
        
        thongKeNam = new ThongKeDoanhThuNam();
      
        add(tabPane, "h 70!, wrap");
        add(thongKeNam, "w 100%, h 100%");
        btnDoanhThuNam.click();
       

    }
    
    
       public void tabSelected(int index){
        if (index == SUB_STATISTICAL_MANAGER.THONG_KE_NAM){
          if (thongKeNam == null){
                thongKeNam = new ThongKeDoanhThuNam();
          }
            showForm(thongKeNam);
        }else if (index == SUB_STATISTICAL_MANAGER.THONG_KE_THANG){
           if (thongKeThang == null){
                thongKeThang = new ThongKeDoanhThuThang();
           }
            showForm(thongKeThang);
        }else if (index == SUB_STATISTICAL_MANAGER.THONG_KE_DICVH){
         if (thongKeDichVu == null){
               thongKeDichVu = new ThongKeDichVu();
         }
            showForm(thongKeDichVu);
        }
    }
       
       
     public void showForm(Component form) {
        remove(getComponentCount()-1);
        add(form, "w 100%, h 100%");
        repaint();
        revalidate();
    }        
      
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JPanel();
        btnDoanhThuNam = new com.ui.swing.component.Tab();
        jLabel1 = new javax.swing.JLabel();
        btnDoanhThuThang = new com.ui.swing.component.Tab();
        jLabel5 = new javax.swing.JLabel();
        btnDichVu = new com.ui.swing.component.Tab();
        jLabel6 = new javax.swing.JLabel();

        tabPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPaneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabPaneMousePressed(evt);
            }
        });

        btnDoanhThuNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoanhThuNamMouseClicked(evt);
            }
        });
        btnDoanhThuNam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Doanh thu năm");
        btnDoanhThuNam.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 40));

        btnDoanhThuThang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoanhThuThangMouseClicked(evt);
            }
        });
        btnDoanhThuThang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Doanh thu tháng");
        btnDoanhThuThang.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 40));

        btnDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDichVuMouseClicked(evt);
            }
        });
        btnDichVu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dịch vụ");
        btnDichVu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        javax.swing.GroupLayout tabPaneLayout = new javax.swing.GroupLayout(tabPane);
        tabPane.setLayout(tabPaneLayout);
        tabPaneLayout.setHorizontalGroup(
            tabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaneLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnDoanhThuNam, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btnDoanhThuThang, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(942, Short.MAX_VALUE))
        );
        tabPaneLayout.setVerticalGroup(
            tabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnDoanhThuThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDoanhThuNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 774, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
     
    
    
    
    
    private void btnDoanhThuNamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoanhThuNamMouseClicked

        btnDoanhThuNam.clear();
        btnDoanhThuThang.clear();
        btnDichVu.clear();
     

        btnDoanhThuNam.click();
        tabSelected(SUB_STATISTICAL_MANAGER.THONG_KE_NAM);
    }//GEN-LAST:event_btnDoanhThuNamMouseClicked

    private void btnDoanhThuThangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoanhThuThangMouseClicked

        btnDoanhThuNam.clear();
        btnDoanhThuThang.clear();
        btnDichVu.clear();
       

        btnDoanhThuThang.click();
        tabSelected(SUB_STATISTICAL_MANAGER.THONG_KE_THANG);
    }//GEN-LAST:event_btnDoanhThuThangMouseClicked

    private void btnDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichVuMouseClicked

        btnDoanhThuNam.clear();
        btnDoanhThuThang.clear();
        btnDichVu.clear();
       

        btnDichVu.click();
        tabSelected(SUB_STATISTICAL_MANAGER.THONG_KE_DICVH);
    }//GEN-LAST:event_btnDichVuMouseClicked

    private void tabPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPaneMouseClicked

    }//GEN-LAST:event_tabPaneMouseClicked

    private void tabPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPaneMousePressed

       
    }//GEN-LAST:event_tabPaneMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ui.swing.component.Tab btnDichVu;
    private com.ui.swing.component.Tab btnDoanhThuNam;
    private com.ui.swing.component.Tab btnDoanhThuThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel tabPane;
    // End of variables declaration//GEN-END:variables
}
